name: GoodsPacker-app workflow

on:
  push:
    branches:
      - '*'
      - '!develop'
      - '!main'

  pull_request:
    branches:
      - 'develop'
      - 'main'
      - 'data_science'

env: 
  DEBUG: 1

jobs:
  tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pep8-naming flake8-broken-line flake8-return flake8-isort
        pip install -r backend/requirements.txt 
    - name: Test with flake8 and django tests
      run: |
        python -m flake8
        cd backend && python manage.py test

  build_and_push_to_docker_hub_data_science:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.base_ref == 'refs/heads/data_science'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker 
        uses: docker/login-action@v1        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push ml to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./ml
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/goods_packer-ml:latest

  build_and_push_to_docker_hub_backend:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    needs: tests
    if: github.base_ref == 'refs/heads/backend'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker 
        uses: docker/login-action@v1        
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push ml to Docker Hub
        uses: docker/build-push-action@v2 
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/goods_packer-backend:latest

  send_message:
    runs-on: ubuntu-latest
    needs: tests
    if: github.base_ref == 'refs/heads/develop' || github.base_ref == 'refs/heads/main' || github.base_ref == 'refs/heads/data_science'
    steps:
    - name: send message
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          ${{ github.workflow }} успешно выполнен в ветку ${{ github.base_ref }} из ветки ${{ github.head_ref }}.
          Commit: ${{ github.sha }}
